
    - name: Download Vagrant .deb
      get_url: url=https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_x86_64.deb dest=/tmp/vagrant_1.9.3_x86_64.deb
      tags:
      - vagrant
      - run
      become: yes
      register: get_url_result
      until: get_url_result | succeeded
      retries: 3
      delay: 1

    - name: Install Vagrant
      apt: deb=/tmp/vagrant_1.9.3_x86_64.deb
      tags:
      - vagrant
      - run
      become: yes
